name: code check

on:   
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  gofmt:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Check out source code
      uses: actions/checkout@v1

    - name: Run go fmt
      run: d="$(gofmt -d ../../)" && if [ -n "$d" ]; then echo "format error:" ; echo "$d"; exit 1; fi      

  staticcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check out source code
      uses: actions/checkout@v1

    - name: Install staticcheck
      run: go get honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck -f stylish ./... 
    - name: Run test
      run: make test
